#makefile get the env parameters when it running in shell
1. env BOARD=mk4 make
2. BOARD=mk4 make

#pass the env parameters in the current makefile to the other makefiles in the subdir
export BOARD=mk4

